### ISSUE TITLE
[Innspill til komponent]: <HelpText />

### ISSUE THREAD

**Issue by BorghildSelle** [navikt/Designsystemet#2603]
### Tilbakemelding

Should not the HelpText Popover have role tooltip? 

https://www.w3.org/WAI/ARIA/apg/patterns/tooltip/

**Comment by KenAJoh** [comment]
Hi 👋 Since our `<HelpText />` does not show on `hover` or `focus` and is not connected to anchor with `aria-describedby` we think the role `tooltip` could be misleading in this case.

In some cases the HelpText could contain quite a bit of information, so to avoid screen readers automatically getting presented this, they can opt to navigate inside the popover if needed.

> The element that triggers the tooltip references the tooltip element with [aria-describedby](https://w3c.github.io/aria/#aria-describedby).

> element when the element receives keyboard focus or the mouse hovers over it

**Comment by BorghildSelle** [comment]
Good point! :)
