### ISSUE TITLE
[Innspill til komponent]: <TextField />

### ISSUE THREAD

**Issue by jennifer-fintlabs** [navikt/Designsystemet#2951]
### Tilbakemelding

Setting type=date in the text field works (i get a date selector) but it is not one of the options, so I get a typescript error. Also, would be nice to have a datetime type.
Thanks.

**Comment by it-vegard** [comment]
We have a custom Datepicker component that serves the same purpose, which is why we don't support the native date selector on TextField: https://aksel.nav.no/komponenter/core/datepicker#datepickerdemo-input-single

DateTime is something we would like to have, but it is not currently on our road map.
