### ISSUE TITLE
<Box>

### ISSUE THREAD

**Issue by JulianNymark** [navikt/Designsystemet#2986]
### Tilbakemelding

Box background prop docs say 'accepts a color token', this seems very generic (all our colors?)

Actual type is named 'BackgroundToken', this seems very constrained (just our bgColors?).

The type then resolves to 'bgColors + surfaceColors'. This is a bit messy, and there could probably be a single transparent term for all of them.

**Comment by KenAJoh** [comment]
Would `Semantic colors` be generic enough?

**Comment by HalvorHaugan** [comment]
Did some improvements to the JSDOC now. When it comes to the type name "BackgroundToken", one could argue that it refers to the prop and not to the actual semantic color tokens, but it's a stretch because of the "Token" suffix.

Suggestions:
- Rename "BackgroundToken" to "BoxBackground".
- Split "BackgroundToken" in two: `background?: BackgroundColorToken | SurfaceColorToken;`
- Do nothing, JSDOC improvement was sufficient.

**Comment by KenAJoh** [comment]
> Split "BackgroundToken" in two: background?: BackgroundColorToken | SurfaceColorToken;

Like this one
