### ISSUE TITLE
[CR] Gjør det mulig med flere undertemaer på God praksis artikler

### ISSUE THREAD

**Issue by sarahbrodwall** [navikt/Designsystemet#3062]
Det virker å være en begrensning at en artikkel kan bare ha én undertema per hovedtema.  Er det en grunn til dette? Ta f.eks. artikkelen om [uu-testing av skjemaer til tilgjengelighetserklæringen](https://aksel.nav.no/god-praksis/artikler/testprotokoll-skjemaer).  UU har undertemaer testing, skjemaer og tilgjengelighetserklæring, men jeg kan bare velge én av disse til artikkelen--den burde ligge i alle undertemaene.  Dessuten bruker undertema et bilde av en tag som ikon. Konseptet "tag" impliserer at det kan være flere per item.  

Kort fortalt: med dagens oppsett kan brukere lett gå glipp av innhold dersom de ikke leter på det riktig sted.

**Comment by sjur-gr** [comment]
Yo! Bra spm. Det er by design i denne versjonen av Aksel. Hovedgrunnen er at datagrunnlaget er så lite at vi fort vil ende opp med at "alle" artikler i et team har samme undertema. Som vil gjøre filtreringen ubrukelig. Vi kommer garantert til å se på organiseringen på nytt etter hvert. En mulighet kan være å gjøre undertemaer globale, mer som tags på ekte. Men det vil kreve en mer robust backend for at det ikke skal bli for mye kluss.
